name: simple_spell_checker
description: "A simple and powerful spell checker, allowing developers to detect and highlight spelling errors in text"
version: 1.2.1
homepage: https://github.com/CatHood0/simple_spell_checker
issue_tracker: https://github.com/CatHood0/simple_spell_checker/issues/
documentation: https://github.com/CatHood0/simple_spell_checker/

topics:
  - ui
  - text-checking
  - highlighting
  - spellchecker 

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
